name: face_recognition
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  camera: ^0.11.0+1
  flutter:
    sdk: flutter
  flutter_face_api: ^6.2.1
  flutter_face_core_basic: ^6.2.1
  # flutter_face_core_match: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  google_mlkit_commons: ^0.7.1
  google_mlkit_face_detection: ^0.11.0
  image: ^4.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  local_auth: ^2.2.0
  path: ^1.9.0
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  rename: ^3.0.2
  sqflite: ^2.3.3+1
  tflite: ^1.1.2
  video_player: ^2.9.1
  # tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/tflite/ssd_mobilenet.tflite
    - assets/tflite/ssd_mobilenet.txt
    - assets/tflite/yolov2_tiny.tflite
    - assets/tflite/yolov2_tiny.txt

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  android_12:
    image: assets/images/icon.png
    color: "#ffffff"
  web: false
